### ISSUE TITLE
Error while running ehs_adsb_wind_extract.py and simulation.py

### ISSUE THREAD

**Issue by ChenhuiAn-git** [junzis/meteo-particle-model#3]
I'm sorry to disturb you, but I encountered a few problems when using the meteo-particle-model. Thank you for your answers.
1.An error occurred while running ehs_adsb_wind_extract.py, the error is shown below：
```
Traceback (most recent call last):
  File "D:/meteo-particle-model-master/extra/ehs_adsb_wind_extract.py", line 78, in <module>
    aggregate()
  File "D:/meteo-particle-model-master/extra/ehs_adsb_wind_extract.py", line 19, in aggregate
    ehs['bds'] = ehs.msg.apply(pms.ehs.BDS)
AttributeError: module 'pyModeS' has no attribute 'ehs'
```
2.An error occurred while running Simulation.py, and the program could not stop normally. The error is as follows:
```
D:/meteo-particle-model-master/extra/simulation.py:102: RuntimeWarning: Degrees of freedom <= 0 for slice
  hmgs = np.linalg.norm(np.cov([PTC_WX[mask], PTC_WY[mask]]))
D:\Anaconda3\envs\traffic01\lib\site-packages\numpy\lib\function_base.py:2455: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
D:\Anaconda3\envs\traffic01\lib\site-packages\numpy\lib\function_base.py:2455: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
```
3.In basemap.py, the dedent function was deprecated in Matplotlib 3.1 and will be removed in 3.3, would you like to improve it?

**Comment by junzis** [comment]
Bugs fixed in 58f7194.
